INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (1,'Aspire');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (2,'Axiom');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (3,'Discovery');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (4,'Loyale');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (5,'Sundance');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (6,'Touareg 2');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (7,'H3');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (8,'Aero 8');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (9,'Stratus');
INSERT INTO vehicle_type(id,vehicle_type_desc) VALUES (10,'Yukon XL 1500');
